FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    docker.io \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    anthropic \
    mcp \
    python-dotenv \
    pydantic \
	requests

COPY server.py .

EXPOSE 8080

CMD ["python", "server.py"]