services:
  gladius-api:
    container_name: gladius-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - net_core
    volumes:
      - ./server.py:/app/server.py
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    ports:
      - "8099:8080"

networks:
  net_core:
    external: true